// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBu07XnPQwDRbUh_VwfXs8nLNHMtQ6cw',
    appId: '1:86189973570:web:8f6b6c5fbb229bb69d4ddb',
    messagingSenderId: '86189973570',
    projectId: 'pixrevive-27081',
    authDomain: 'pixrevive-27081.firebaseapp.com',
    storageBucket: 'pixrevive-27081.firebasestorage.app',
    measurementId: 'G-ZLETNPRC24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLmvPjV7CZPk7TJPg59q6bKttAkz3sBmk',
    appId: '1:86189973570:android:ab96117cdaa8d6d79d4ddb',
    messagingSenderId: '86189973570',
    projectId: 'pixrevive-27081',
    storageBucket: 'pixrevive-27081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPa-Vc0tZ2eFg17bVjv7dax1-nkme1QE',
    appId: '1:86189973570:ios:3009419aefa1da909d4ddb',
    messagingSenderId: '86189973570',
    projectId: 'pixrevive-27081',
    storageBucket: 'pixrevive-27081.firebasestorage.app',
    iosBundleId: 'com.example.pixRevive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPa-Vc0tZ2eFg17bVjv7dax1-nkme1QE',
    appId: '1:86189973570:ios:3009419aefa1da909d4ddb',
    messagingSenderId: '86189973570',
    projectId: 'pixrevive-27081',
    storageBucket: 'pixrevive-27081.firebasestorage.app',
    iosBundleId: 'com.example.pixRevive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrBu07XnPQwDRbUh_VwfXs8nLNHMtQ6cw',
    appId: '1:86189973570:web:f8fb05b61740d3989d4ddb',
    messagingSenderId: '86189973570',
    projectId: 'pixrevive-27081',
    authDomain: 'pixrevive-27081.firebaseapp.com',
    storageBucket: 'pixrevive-27081.firebasestorage.app',
    measurementId: 'G-E51NVTV4XW',
  );
}
